USE [master]
GO

/****** Object:  Database [Ferchau]    Script Date: 16.12.2022 11:07:52 ******/
CREATE DATABASE [Ferchau]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Frechau', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Frechau.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Frechau_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Frechau_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ferchau].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ferchau] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ferchau] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ferchau] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ferchau] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ferchau] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ferchau] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ferchau] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ferchau] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ferchau] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ferchau] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ferchau] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ferchau] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ferchau] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ferchau] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ferchau] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ferchau] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ferchau] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ferchau] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ferchau] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ferchau] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ferchau] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ferchau] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ferchau] SET RECOVERY FULL 
GO

ALTER DATABASE [Ferchau] SET  MULTI_USER 
GO

ALTER DATABASE [Ferchau] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ferchau] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ferchau] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ferchau] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ferchau] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ferchau] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ferchau] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ferchau] SET  READ_WRITE 
GO

